# Generated by Django 5.0 on 2024-10-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='imeges',
            field=models.ImageField(default='ninja.jpg', upload_to='static/images'),
        ),
    ]
